### ISSUE TITLE
Error when trying to use SATRN model

### ISSUE THREAD

**Issue by fattynoparents** [AI-Riksarkivet/htrflow#21]
### What happened?

How to use the `Riksarkivet/satrn_htr` model with htrflow? 
When trying to add it to the pipeline config and run ` htrflow pipeline pipeline 1.jpg` I get the following error:
```
NotImplementedError: Model satrn_htr is not supported. The available models are: DiT, LLavaNext, TrOCR, WordLevelTrOCR, YOLO.
```
The same happens if I try to use the `Riksarkivet/rtmdet_lines` model for segmentation.

The `yolo` and `Riksarkivet/trocr-base-handwritten-hist-swe-2` models work fine.

**Comment by albpedmul** [comment]
maybe this will help
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
If you don't have the c compliator, install it.(gcc or clang)

**Comment by fattynoparents** [comment]
Thanks I have managed to use the Satrn model in a Python 3.10 environment after having installed the mmocr, mmdet and mmcv packages.
